version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=app
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  psql:
    image: postgres:latest
    depends_on:
      - postgres
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command: psql -U docker -d app -f /docker-entrypoint-initdb.d/script.sql
# docker-compose up
