### Use a extensão do VSCode - REST Client (Huachao Mao)

GET http://localhost:8080/users

###

GET http://localhost:8080/user/18

###

POST http://localhost:8080/user HTTP/1.1
content-type: application/json

{
    "email": "user1@user.com",
    "password": "1234"
}

###

PUT http://localhost:8080/user HTTP/1.1
content-type: application/json

{
    "id": "18",
    "email": "super.user@user.com",
    "password": "12345678"
}

###

DELETE http://localhost:8080/user HTTP/1.1
content-type: application/json

{
    "id": "16"
}