### Use a extensão do VSCode - REST Client (Huachao Mao)

GET http://localhost:8080/users

###

GET http://localhost:8080/user/1

###

POST http://localhost:8080/user HTTP/1.1
content-type: application/json

{
    "name": "User RMS",
    "email": "rms@localhost.com",
    "password": "1234"
}

###

PUT http://localhost:8080/user HTTP/1.1
content-type: application/json

{
    "id": "50",
    "name": "User RMS",
    "email": "rms@app.com",
    "password": "123456789"
}

###

DELETE http://localhost:8080/user HTTP/1.1
content-type: application/json

{
    "id": "1"
}